sudo: required
dist: trusty

language:
  - python

python:
  - "3.6"

services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

env:
  - DJANGO_SETTINGS_MODULE=workflow_tasks.settings.testing

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres


before_install:
  - sudo apt-get update

install:
  - pip install -r requirements/dev.txt


script:
  - python manage.py test
