# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 16:18
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELED', 'Canceled'), ('COMPLETED', 'Completed')], db_index=True, default='ACTIVE', max_length=50)),
                ('priority', models.IntegerField(default=0)),
                ('assignable_from', models.DateTimeField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('assignee_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='TaskValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('key', models.CharField(db_index=True, max_length=50)),
                ('value_content_type', models.CharField(choices=[('INTEGER', 'Integer'), ('STRING', 'String'), ('DATETIME', 'Datetime')], db_index=True, max_length=50)),
                ('value', models.TextField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='workflows.Task')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('label', models.CharField(max_length=100)),
                ('internal_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('snoozing', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workflows.WorkflowBase'),
        ),
    ]
